#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <assert.h>

static const char *delims = "@[]:<>(),&|~=; \t\n\r";
static const char *variable_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_";
static const char *all_keywords[] = {
    "BITVECTOR",
    "BOOLEAN",
    "ARRAY",
    "OF",
    "ASSERT",
    "QUERY",
    "COUNTEREXAMPLE",
    "TRUE",
    "FALSE",
    "NOT",
    "BVSX",
    "WITH",
    "BVXOR",
    "BVNAND",
    "BVNOR",
    "BVXNOR",
    "BVPLUS",
    "BVMULT",
    "BVSUB",
    "BVUMINUS",
    "BVDIV",
    "SBVDIV",
    "BVMOD",
    "SBVMOD",
    "BVLT",
    "BVGT",
    "BVLE",
    "BVGE",
    "BVSLT",
    "BVSGT",
    "BVSLE",
    "BVSGE",
    "SBVLT",
    "SBVGT",
    "SBVLE",
    "SBVGE",
    "IF",
    "THEN",
    "ELSE",
    "ENDIF",
};

/* For debugging (in case I forgot a keyword).
 * If this fits the kind of name we expect to see generated by catchconv
 * (in particular, it starts with CV, JUMPCOND, or INPUT_MEM), return 1.
 * Otherwise, return 0.  The latter case may help us to find omissions
 * in the all_keywords list above. */
int normalname(char *p) {
    if (strncmp(p, "CV", 2) != 0 && strncmp(p, "JUMPCOND", 8) != 0
            && strncmp(p, "INPUT_MEM", 9) != 0)
        return 0;
    if ('0' <= *p && *p <= '9')
        return 0;
    if (strspn(p, variable_chars) < strlen(p))
        return 0;
    return 1;
}

unsigned int hash(const char *p) {
    unsigned int hash = 5381, c;
    while ((c = *p++) != '\0') {
        hash = ((hash << 5) + hash) ^ c;
    }
    return hash;
}

#define KW_SIZE 1021
static const char *keywords[KW_SIZE];

void addkeyword(const char *word) {
    unsigned int h = hash(word);
    unsigned int i;
    for (i = h % KW_SIZE; keywords[i] != NULL; i = (i+h+77) % KW_SIZE)
        if (strcmp(keywords[i], word) == 0)
            assert(0);
    keywords[i] = word;
}
void init_keywords(void) {
    int i;
    for (i=0; i<sizeof(all_keywords)/sizeof(char *); i++)
        addkeyword(all_keywords[i]);
}
int iskeyword(const char *word) {
    unsigned int h = hash(word);
    unsigned int i;
    for (i = h % KW_SIZE; keywords[i] != NULL; i = (i+h+77) % KW_SIZE)
        if (strcmp(keywords[i], word) == 0)
            return 1;
    return 0;
}

int isconstant(char *p) {
    int len = strlen(p);
    if (strspn(p, "0123456789") == len)
        return 1;
    if (len > 4 && strncmp(p, "0bin", 4) == 0
            && strspn(p+4, "01") == (len-4))
        return 1;
    if (len > 4 && strncmp(p, "0hex", 4) == 0
            && strspn(p+4, "0123456789ABCDEFabcdef") == (len-4))
        return 1;
    return 0;
}

#define VAR_SIZE 16777213 // = 2^24 - 3 (which is prime)
static char *variables[VAR_SIZE];
void addvariable(const char *var) {
    unsigned int h = hash(var);
    unsigned int i;
    for (i = h % VAR_SIZE; variables[i] != NULL; i = (i+h+777) % VAR_SIZE)
        if (strcmp(variables[i], var) == 0)
            return;
    variables[i] = strdup(var);
}

void parseline(char *line) {
    char *tok;
    for (tok = strtok(line, delims); tok != NULL; tok = strtok(NULL, delims)) {
            if (isconstant(tok))
                continue;
            if (iskeyword(tok))
                continue;
            /* Okay, we've got a variable name.  For this simple example
             * we just add it to a global hash table, but we could do
             * anything else with the list of variables on this line. */
            addvariable(tok);
    }
}


int main() {
    char buf[8192], *p;
    int i, n=0;

    init_keywords();

    while (fgets(buf, sizeof buf, stdin) != NULL) {
        p = buf;
        while (isspace(*p))
            p++;
        if (*p == '\0' || strncmp(p, "XXX", 3) == 0)
            continue;
        assert(strchr(p, '\n') != NULL);
        parseline(p);
    }

    for (i=0; i < VAR_SIZE; i++)
        if ((p = variables[i]) != NULL) {
            n++;
            printf("%s\n", p);
            /* A very helpful debugging tool. */
            if (!normalname(p))
                fprintf(stderr, "Unexpected variable name: %s\n", p);
        }
    printf("Saw %d variable names\n", n);

    return 0;
}
